# Site settings
title: Garrett's Blog
description: Writing about the intersection of technology leadership and business acumen

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Google Analytics
google_analytics: G-TF81W7GBW7
